name: Release Plugin

on:
  push:
    tags:
      - "v*" # Trigger the workflow on version tags, e.g., v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Adjust as per your needs

      - name: Install dependencies
        run: npm install

      - name: Build Plugin
        run: npm run build # Adjust if your build script is different

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          files: |
            dist/*  # Adjust if your built files are located elsewhere
